# Generated by Django 5.0.4 on 2024-05-09 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llistaproductes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='llistaproductes',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
