# Generated by Django 5.0.4 on 2024-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0002_carreto_created_at_carreto_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreto',
            name='estaActiu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carreto',
            name='pagat',
            field=models.BooleanField(default=False),
        ),
    ]
