# Generated by Django 5.0.4 on 2024-05-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto')),
            ],
        ),
    ]
