# Generated by Django 5.0.4 on 2024-05-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagat', models.BooleanField(default=False)),
                ('ordre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comandes.ordre')),
            ],
        ),
    ]
